name: Publish to NPM

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: "latest"

      - name: Install dependencies
        run: bun install

      - name: Install build
        run: bun run build

      - name: Publish to npm
        run: bun publish --access=public
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
